# Form implementation generated from reading ui file 'forgotpassvalidation.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_forgotPassword(object):
    def setupUi(self, forgotPassword):
        forgotPassword.setObjectName("forgotPassword")
        forgotPassword.resize(497, 401)
        forgotPassword.setStyleSheet("QLineEdit{\n"
"background-color: rgb(144, 206, 103)\n"
"}")
        self.changePassSubmitBtn = QtWidgets.QPushButton(parent=forgotPassword)
        self.changePassSubmitBtn.setGeometry(QtCore.QRect(340, 340, 111, 31))
        self.changePassSubmitBtn.setStyleSheet("QPushButton{border: none;\n"
"background-color: rgb(0, 255, 0);\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5CE371\n"
"}")
        self.changePassSubmitBtn.setObjectName("changePassSubmitBtn")
        self.forgotPassCancelBtn = QtWidgets.QPushButton(parent=forgotPassword)
        self.forgotPassCancelBtn.setGeometry(QtCore.QRect(210, 340, 111, 31))
        self.forgotPassCancelBtn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"border: none;\n"
"background-color: #E35C5C;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 79, 79);\n"
"    \n"
"}")
        self.forgotPassCancelBtn.setObjectName("forgotPassCancelBtn")
        self.changePassSubmitBtn_2 = QtWidgets.QPushButton(parent=forgotPassword)
        self.changePassSubmitBtn_2.setEnabled(True)
        self.changePassSubmitBtn_2.setGeometry(QtCore.QRect(340, 340, 111, 31))
        self.changePassSubmitBtn_2.setStyleSheet("QPushButton{border: none;\n"
"background-color: rgb(0, 255, 0);\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5CE371\n"
"}")
        self.changePassSubmitBtn_2.setObjectName("changePassSubmitBtn_2")
        self.layoutWidget = QtWidgets.QWidget(parent=forgotPassword)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 33, 431, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 35)
        self.gridLayout.setVerticalSpacing(17)
        self.gridLayout.setObjectName("gridLayout")
        self.ans2Input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ans2Input.setObjectName("ans2Input")
        self.gridLayout.addWidget(self.ans2Input, 7, 1, 1, 1)
        self.adminIDInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.adminIDInput.setText("")
        self.adminIDInput.setObjectName("adminIDInput")
        self.gridLayout.addWidget(self.adminIDInput, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.q1label = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.q1label.setEnabled(False)
        self.q1label.setObjectName("q1label")
        self.gridLayout.addWidget(self.q1label, 4, 1, 1, 1)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.gridLayout.addWidget(self.usernameInput, 3, 1, 1, 1)
        self.ansInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ansInput.setObjectName("ansInput")
        self.gridLayout.addWidget(self.ansInput, 5, 1, 1, 1)
        self.adminIDLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.adminIDLabel.setObjectName("adminIDLabel")
        self.gridLayout.addWidget(self.adminIDLabel, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.q2label = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.q2label.setEnabled(False)
        self.q2label.setObjectName("q2label")
        self.gridLayout.addWidget(self.q2label, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.usernameLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 3, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)

        self.retranslateUi(forgotPassword)
        QtCore.QMetaObject.connectSlotsByName(forgotPassword)

    def retranslateUi(self, forgotPassword):
        _translate = QtCore.QCoreApplication.translate
        forgotPassword.setWindowTitle(_translate("forgotPassword", "Forgot Password"))
        self.changePassSubmitBtn.setText(_translate("forgotPassword", "Submit"))
        self.forgotPassCancelBtn.setText(_translate("forgotPassword", "Cancel"))
        self.changePassSubmitBtn_2.setText(_translate("forgotPassword", "Submit"))
        self.label_7.setText(_translate("forgotPassword", "Answer"))
        self.adminIDLabel.setText(_translate("forgotPassword", "Admin ID:"))
        self.label_4.setText(_translate("forgotPassword", "Answer"))
        self.label_2.setText(_translate("forgotPassword", "Question 1:"))
        self.label.setText(_translate("forgotPassword", "<html><head/><body><p align=\"center\">Change Password</p></body></html>"))
        self.usernameLabel.setText(_translate("forgotPassword", "Username:"))
        self.titleLabel.setText(_translate("forgotPassword", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">HomeFix Pest and Termite Control </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">Managment System</span></p></body></html>"))
        self.label_5.setText(_translate("forgotPassword", "Question 2:"))
