# Form implementation generated from reading ui file 'AddClients.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addClients(object):
    def setupUi(self, addClients):
        addClients.setObjectName("addClients")
        addClients.resize(444, 386)
        addClients.setStyleSheet("QPushButton{\n"
"    height:100%\n"
"}\n"
"")
        self.label_16 = QtWidgets.QLabel(parent=addClients)
        self.label_16.setGeometry(QtCore.QRect(20, 0, 251, 81))
        self.label_16.setLineWidth(0)
        self.label_16.setScaledContents(False)
        self.label_16.setIndent(3)
        self.label_16.setObjectName("label_16")
        self.cancelBtn = QtWidgets.QPushButton(parent=addClients)
        self.cancelBtn.setGeometry(QtCore.QRect(191, 320, 91, 41))
        self.cancelBtn.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: #E35C5C;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 79, 79);\n"
"    \n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.addclientBtn = QtWidgets.QPushButton(parent=addClients)
        self.addclientBtn.setGeometry(QtCore.QRect(300, 320, 101, 41))
        self.addclientBtn.setStyleSheet("QPushButton{border: none;\n"
"background-color: rgb(0, 255, 0);\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5CE371\n"
"}")
        self.addclientBtn.setObjectName("addclientBtn")
        self.widget = QtWidgets.QWidget(parent=addClients)
        self.widget.setGeometry(QtCore.QRect(30, 100, 371, 237))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(26)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.nameInput = QtWidgets.QLineEdit(parent=self.widget)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.emailInput = QtWidgets.QLineEdit(parent=self.widget)
        self.emailInput.setObjectName("emailInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailInput)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.phonenumInput = QtWidgets.QLineEdit(parent=self.widget)
        self.phonenumInput.setObjectName("phonenumInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phonenumInput)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.addressInput = QtWidgets.QLineEdit(parent=self.widget)
        self.addressInput.setObjectName("addressInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addressInput)

        self.retranslateUi(addClients)
        QtCore.QMetaObject.connectSlotsByName(addClients)

    def retranslateUi(self, addClients):
        _translate = QtCore.QCoreApplication.translate
        addClients.setWindowTitle(_translate("addClients", "Dialog"))
        self.label_16.setText(_translate("addClients", "<html><head/><body><p><span style=\" font-size:24pt;\">Add Client</span></p></body></html>"))
        self.cancelBtn.setText(_translate("addClients", "Cancel"))
        self.addclientBtn.setText(_translate("addClients", "Add Client"))
        self.label.setText(_translate("addClients", "Name"))
        self.label_2.setText(_translate("addClients", "Email"))
        self.label_3.setText(_translate("addClients", "PhoneNumber"))
        self.label_4.setText(_translate("addClients", "Address"))
