# Form implementation generated from reading ui file 'forgotpassvalidation.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_forgotPassword(object):
    def setupUi(self, forgotPassword):
        forgotPassword.setObjectName("forgotPassword")
        forgotPassword.resize(358, 300)
        forgotPassword.setMinimumSize(QtCore.QSize(358, 300))
        forgotPassword.setMaximumSize(QtCore.QSize(358, 300))
        self.forgotPassSubmitBtn = QtWidgets.QPushButton(parent=forgotPassword)
        self.forgotPassSubmitBtn.setGeometry(QtCore.QRect(210, 250, 111, 31))
        self.forgotPassSubmitBtn.setStyleSheet("QPushButton{border: none;\n"
"background-color: rgb(0, 255, 0);\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5CE371\n"
"}")
        self.forgotPassSubmitBtn.setObjectName("forgotPassSubmitBtn")
        self.forgotPassCancelBtn = QtWidgets.QPushButton(parent=forgotPassword)
        self.forgotPassCancelBtn.setGeometry(QtCore.QRect(80, 250, 111, 31))
        self.forgotPassCancelBtn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"border: none;\n"
"background-color: #E35C5C;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 79, 79);\n"
"    \n"
"}")
        self.forgotPassCancelBtn.setObjectName("forgotPassCancelBtn")
        self.layoutWidget = QtWidgets.QWidget(parent=forgotPassword)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 291, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.titleLabel)
        self.adminIDLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.adminIDLabel.setObjectName("adminIDLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.adminIDLabel)
        self.adminIDInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.adminIDInput.setObjectName("adminIDInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.adminIDInput)
        self.usernameLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usernameInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, spacerItem1)

        self.retranslateUi(forgotPassword)
        QtCore.QMetaObject.connectSlotsByName(forgotPassword)

    def retranslateUi(self, forgotPassword):
        _translate = QtCore.QCoreApplication.translate
        forgotPassword.setWindowTitle(_translate("forgotPassword", "Forgot Password"))
        self.forgotPassSubmitBtn.setText(_translate("forgotPassword", "Submit"))
        self.forgotPassCancelBtn.setText(_translate("forgotPassword", "Cancel"))
        self.titleLabel.setText(_translate("forgotPassword", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">HomeFix Pest and Termite Control </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">Managment System</span></p></body></html>"))
        self.adminIDLabel.setText(_translate("forgotPassword", "Admin ID:"))
        self.usernameLabel.setText(_translate("forgotPassword", "Username:"))
        self.label.setText(_translate("forgotPassword", "<html><head/><body><p align=\"center\">Change Password</p></body></html>"))
