from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addcontract(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 513)
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(250, 450, 75, 24))
        self.cancelBtn.setObjectName("cancelBtn")
        self.addBtn = QtWidgets.QPushButton(parent=Dialog)
        self.addBtn.setGeometry(QtCore.QRect(360, 450, 75, 24))
        self.addBtn.setObjectName("addBtn")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 220, 341, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.startInput = QtWidgets.QDateEdit(parent=self.widget)
        self.startInput.setObjectName("startInput")
        self.horizontalLayout.addWidget(self.startInput)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.endInput = QtWidgets.QDateEdit(parent=self.widget)
        self.endInput.setObjectName("endInput")
        self.horizontalLayout.addWidget(self.endInput)
        self.widget1 = QtWidgets.QWidget(parent=Dialog)
        self.widget1.setGeometry(QtCore.QRect(60, 80, 301, 101))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.typeInput = QtWidgets.QLineEdit(parent=self.widget1)
        self.typeInput.setObjectName("typeInput")
        self.gridLayout.addWidget(self.typeInput, 1, 1, 1, 1)
        self.problemInput = QtWidgets.QLineEdit(parent=self.widget1)
        self.problemInput.setObjectName("problemInput")
        self.gridLayout.addWidget(self.problemInput, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(parent=Dialog)
        self.widget2.setGeometry(QtCore.QRect(70, 270, 311, 121))
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.unitInput = QtWidgets.QLineEdit(parent=self.widget2)
        self.unitInput.setObjectName("unitInput")
        self.gridLayout_2.addWidget(self.unitInput, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.scopeInput = QtWidgets.QLineEdit(parent=self.widget2)
        self.scopeInput.setObjectName("scopeInput")
        self.gridLayout_2.addWidget(self.scopeInput, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.priceInput = QtWidgets.QLineEdit(parent=self.widget2)
        self.priceInput.setObjectName("priceInput")
        self.gridLayout_2.addWidget(self.priceInput, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.widget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.widget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.widget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.addBtn.setText(_translate("Dialog", "Add"))
        self.label_4.setText(_translate("Dialog", "Contract Period: "))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Start: </p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">End:</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Type of Treatment: "))
        self.label.setText(_translate("Dialog", "Main Problem:"))
        self.label_3.setText(_translate("Dialog", "Price"))
        self.label_5.setText(_translate("Dialog", "Scope"))
        self.label_6.setText(_translate("Dialog", "No. of Units"))
        self.label_9.setText(_translate("Dialog", "sq. meters"))
        self.label_10.setText(_translate("Dialog", "units/room"))
        self.label_11.setText(_translate("Dialog", "pesos"))
