from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 439)
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(214, 370, 111, 41))
        self.cancelBtn.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background-color: #E35C5C;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 79, 79);\n"
"    \n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.addBtn = QtWidgets.QPushButton(parent=Dialog)
        self.addBtn.setGeometry(QtCore.QRect(350, 370, 111, 41))
        self.addBtn.setStyleSheet("QPushButton{border: none;\n"
"background-color: rgb(0, 255, 0);\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5CE371\n"
"}")
        self.addBtn.setObjectName("addBtn")
        self.label_17 = QtWidgets.QLabel(parent=Dialog)
        self.label_17.setGeometry(QtCore.QRect(20, 10, 251, 81))
        self.label_17.setLineWidth(0)
        self.label_17.setScaledContents(False)
        self.label_17.setIndent(3)
        self.label_17.setObjectName("label_17")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 90, 431, 251))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(21)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.typeInput = QtWidgets.QLineEdit(parent=self.widget)
        self.typeInput.setObjectName("typeInput")
        self.gridLayout.addWidget(self.typeInput, 1, 1, 1, 1)
        self.problemInput = QtWidgets.QLineEdit(parent=self.widget)
        self.problemInput.setObjectName("problemInput")
        self.gridLayout.addWidget(self.problemInput, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.startInput = QtWidgets.QDateEdit(parent=self.widget)
        self.startInput.setObjectName("startInput")
        self.horizontalLayout.addWidget(self.startInput)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.endInput = QtWidgets.QDateEdit(parent=self.widget)
        self.endInput.setObjectName("endInput")
        self.horizontalLayout.addWidget(self.endInput)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(26)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.unitInput = QtWidgets.QLineEdit(parent=self.widget)
        self.unitInput.setObjectName("unitInput")
        self.gridLayout_2.addWidget(self.unitInput, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.scopeInput = QtWidgets.QLineEdit(parent=self.widget)
        self.scopeInput.setObjectName("scopeInput")
        self.gridLayout_2.addWidget(self.scopeInput, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.addBtn.setText(_translate("Dialog", "Add"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Add Contract</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Type of Treatment: "))
        self.label.setText(_translate("Dialog", "Main Problem:"))
        self.label_4.setText(_translate("Dialog", "Contract Period: "))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Start: </p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">End:</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Price"))
        self.label_5.setText(_translate("Dialog", "Scope"))
        self.label_6.setText(_translate("Dialog", "No. of Units"))
        self.label_9.setText(_translate("Dialog", "sq. meters"))
        self.label_10.setText(_translate("Dialog", "units/room"))
        self.label_11.setText(_translate("Dialog", "pesos"))
