
from PyQt6 import QtCore, QtGui, QtWidgets


class EditClient(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(507, 400)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 70, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 49, 16))
        self.label_4.setObjectName("label_4")
        self.nameInput = QtWidgets.QLineEdit(parent=Dialog)
        self.nameInput.setGeometry(QtCore.QRect(140, 70, 141, 22))
        self.nameInput.setObjectName("nameInput")
        self.contactnoInput = QtWidgets.QLineEdit(parent=Dialog)
        self.contactnoInput.setGeometry(QtCore.QRect(140, 130, 131, 22))
        self.contactnoInput.setObjectName("contactnoInput")
        self.locationInput = QtWidgets.QLineEdit(parent=Dialog)
        self.locationInput.setGeometry(QtCore.QRect(130, 190, 151, 22))
        self.locationInput.setObjectName("locationInput")
        self.emailInput = QtWidgets.QLineEdit(parent=Dialog)
        self.emailInput.setGeometry(QtCore.QRect(140, 250, 141, 22))
        self.emailInput.setObjectName("emailInput")
        self.nameBtn = QtWidgets.QPushButton(parent=Dialog)
        self.nameBtn.setGeometry(QtCore.QRect(380, 70, 75, 24))
        self.nameBtn.setObjectName("nameBtn")
        self.contactnoBtn = QtWidgets.QPushButton(parent=Dialog)
        self.contactnoBtn.setGeometry(QtCore.QRect(380, 120, 75, 24))
        self.contactnoBtn.setObjectName("contactnoBtn")
        self.locationBtn = QtWidgets.QPushButton(parent=Dialog)
        self.locationBtn.setGeometry(QtCore.QRect(380, 190, 75, 24))
        self.locationBtn.setObjectName("locationBtn")
        self.emailBtn = QtWidgets.QPushButton(parent=Dialog)
        self.emailBtn.setGeometry(QtCore.QRect(380, 250, 75, 24))
        self.emailBtn.setObjectName("emailBtn")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(380, 350, 75, 24))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Contact No."))
        self.label_3.setText(_translate("Dialog", "Address"))
        self.label_4.setText(_translate("Dialog", "Email"))
        self.nameBtn.setText(_translate("Dialog", "Confirm"))
        self.contactnoBtn.setText(_translate("Dialog", "Confirm"))
        self.locationBtn.setText(_translate("Dialog", "Confirm"))
        self.emailBtn.setText(_translate("Dialog", "Confirm"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
