# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setEnabled(True)
        login.resize(360, 300)
        login.setMinimumSize(QtCore.QSize(360, 300))
        login.setMaximumSize(QtCore.QSize(360, 300))
        login.setBaseSize(QtCore.QSize(360, 300))
        login.setStyleSheet("QWidget{\n"
"background-color:rgb(45, 116, 1)\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:white\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    height: 100%;\n"
"    width: 100%;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left:10px;\n"
"    background-color: rgb(244, 252, 245)\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"         background-color: rgb(182, 223, 154);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"         background-color: rgb(182, 223, 154);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(182, 223, 154);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=login)
        self.centralwidget.setObjectName("centralwidget")
        self.forgotpassworBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.forgotpassworBtn.setGeometry(QtCore.QRect(210, 200, 121, 31))
        self.forgotpassworBtn.setStyleSheet("QPushButton:hover{\n"
"color:blue;\n"
"}\n"
"\n"
"QPushButton{\n"
"border: none;\n"
"text-decoration: underline;\n"
"background-color: rgb(45, 116, 1);\n"
"color: white;\n"
"}")
        self.forgotpassworBtn.setCheckable(False)
        self.forgotpassworBtn.setObjectName("forgotpassworBtn")
        self.submitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitBtn.setGeometry(QtCore.QRect(220, 250, 111, 31))
        self.submitBtn.setStyleSheet("QPushButton {background-color:rgb(217, 217, 217); color: black;}")
        self.submitBtn.setObjectName("submitBtn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 308, 165))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.titleLabel)
        self.adminIDLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.adminIDLabel.setObjectName("adminIDLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.adminIDLabel)
        self.adminIDInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.adminIDInput.setObjectName("adminIDInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.adminIDInput)
        self.usernameLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.passwordLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.passwordLabel)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.passwordInput.setEnabled(True)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordInput)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usernameInput)
        login.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=login)
        self.statusBar.setObjectName("statusBar")
        login.setStatusBar(self.statusBar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login"))
        self.forgotpassworBtn.setText(_translate("login", "Forgot Password?"))
        self.submitBtn.setText(_translate("login", "Submit"))
        self.titleLabel.setText(_translate("login", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">HomeFix Pest and Termite Control </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">Managment System</span></p></body></html>"))
        self.adminIDLabel.setText(_translate("login", "Admin ID:"))
        self.usernameLabel.setText(_translate("login", "Username:"))
        self.passwordLabel.setText(_translate("login", "Password:"))
